### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by sinanopcommerce** [manuelbl/QrCodeGenerator#27]
'QrCodeGenerator, Version=1.6.0.0, Culture=neutral, PublicKeyToken=6aa6bd7a159d47c2, processorArchitecture=MSIL'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at Nop.Core.Infrastructure.AppDomainTypeFinder.LoadMatchingAssemblies(String directoryPath)
   at Nop.Core.Infrastructure.WebAppTypeFinder.GetAssemblies()
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, WebApplicationBuilder builder)
   at Program.<Main>$(String[] args)
Aborted (core dumped)

**Comment by manuelbl** [comment]
By dumping a stack trace into an issue, I guess you are seeking for help to solve this problem. Or have you already solved it and just want to let me know that... More information would be appreciated.

A stack trace usually starts with an exception (Unhandled exception. System.IO.DirectoryNotFoundException: ...). Did you not copy it that text, or was there no exception?

For a further analysis, more information is needed: operating system, .NET version, full error message, any helpful information, possibly code to reproduce it.
